import psycopg2
import json
import os

# Load config
base_dir = os.path.dirname(__file__)
config_path = os.path.join(base_dir, "DBModelGenerator.json")
with open(config_path, "r") as f:
    config = json.load(f)

output_dir = os.path.abspath(os.path.join(base_dir, config["OutputDir"]))
os.makedirs(output_dir, exist_ok=True)

ns = config["Namespace"]
connection_string = config["ConnectionString"]
scope = config["Scope"]
Depluralize = config.get("Depluralize", "false").lower() == "true"
add_validation_annotations = config.get("IncludeAnnotations", "false").lower() == "true"

# Helpers
def get_class_name(table_name: str) -> str:
    if Depluralize:
        if table_name.endswith("ies"):
            return table_name[:-3] + "y"
        elif table_name.endswith("s"):
            return table_name[:-1]
    return table_name

def map_sql_type(sql_type: str) -> str:
    sql_type = sql_type.lower()
    if sql_type in ("boolean", "bool"):
        return "bool"
    elif sql_type in ("smallint"):
        return "short"
    elif sql_type in ("integer", "int4"):
        return "int"
    elif sql_type in ("bigint", "int8"):
        return "long"
    elif sql_type in ("real", "float4"):
        return "float"
    elif sql_type in ("double precision", "float8"):
        return "double"
    elif sql_type in ("numeric", "decimal", "money"):
        return "decimal"
    elif sql_type in ("character varying", "varchar", "text", "char", "citext"):
        return "string"
    elif sql_type in ("date", "timestamp", "timestamp without time zone", "timestamp with time zone"):
        return "DateTime"
    elif sql_type in ("time", "time without time zone", "time with time zone"):
        return "TimeSpan"
    elif sql_type in ("uuid"):
        return "Guid"
    elif sql_type in ("bytea"):
        return "byte[]"
    elif sql_type in ("json", "jsonb"):
        return "string"
    else:
        return "string"

# Connect
conn = psycopg2.connect(connection_string)
cur = conn.cursor()

# Get tables
cur.execute("""
    SELECT table_name, table_schema
    FROM information_schema.tables
    WHERE table_schema NOT IN ('pg_catalog','information_schema');
""")
tables = cur.fetchall()

for table_name, table_schema in tables:
    class_name = get_class_name(table_name)

    # Collect PKs
    pk_columns = set()
    cur.execute("""
        SELECT kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema = kcu.table_schema
        WHERE tc.constraint_type = 'PRIMARY KEY'
          AND tc.table_name = %s
          AND tc.table_schema = %s;
    """, (table_name, table_schema))
    for row in cur.fetchall():
        pk_columns.add(row[0])

    # Identity columns
    identity_columns = set()
    cur.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = %s
          AND table_schema = %s
          AND is_identity = 'YES';
    """, (table_name, table_schema))
    for row in cur.fetchall():
        identity_columns.add(row[0])

    # Foreign keys
    fk_map = {}
    cur.execute("""
        SELECT kcu.column_name, ccu.table_name, ccu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
        JOIN information_schema.constraint_column_usage ccu
          ON ccu.constraint_name = tc.constraint_name
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND kcu.table_name = %s
          AND kcu.table_schema = %s;
    """, (table_name, table_schema))
    for fk_col, pk_table, pk_col in cur.fetchall():
        fk_map[fk_col] = (pk_table, pk_col)

    # Computed/generated columns
    computed_columns = set()
    cur.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = %s
          AND table_schema = %s
          AND generation_expression IS NOT NULL;
    """, (table_name, table_schema))
    for row in cur.fetchall():
        computed_columns.add(row[0])

    # Build class
    class_code = []
    append_class_code = []

    class_code.append("using System;")
    class_code.append("using System.ComponentModel.DataAnnotations;")
    class_code.append("using System.ComponentModel.DataAnnotations.Schema;")
    class_code.append("")
    class_code.append("/// Auto Generated by DBModelGenerator.py - do not modify")
    class_code.append(f"namespace {ns}")
    class_code.append("{")
    class_code.append(f"    {scope} partial class {class_name}")
    class_code.append("    {")

    # Columns
    cur.execute("""
        SELECT column_name, data_type, is_nullable, column_default, character_maximum_length
        FROM information_schema.columns
        WHERE table_name = %s AND table_schema = %s
        ORDER BY ordinal_position;
    """, (table_name, table_schema))
    for col_name, data_type, is_nullable, column_default, char_max_len in cur.fetchall():
        cs_type = map_sql_type(data_type)
        is_required = (is_nullable == "NO")
        is_pk = col_name in pk_columns
        has_default = column_default is not None

        # Do not mess with the nullability markers, this is for Blazor and default values. If you want to make a property required, use the [Required] annotation.
        is_nullable_type = (add_validation_annotations or has_default or not is_required) and not is_pk 
        nullable_marker = "?" if is_nullable_type else ""

        # Annotations
        if is_pk:
            class_code.append("        [Key]")
        if col_name in pk_columns and column_default and "nextval" in column_default:
            class_code.append("        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]")
        elif col_name in computed_columns:
            class_code.append("        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]")
            class_code.append("        [Editable(false)]")
        elif has_default:
            class_code.append("        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]")


        if col_name in fk_map:
            pk_table, pk_col = fk_map[col_name]
            fk_class = get_class_name(pk_table)
            fk_nav_prop = col_name[:-2] if col_name.lower().endswith("id") else col_name + fk_class
            class_code.append(f'        [ForeignKey("{fk_nav_prop}")]')
            append_class_code.append(f"        public {fk_class}? {fk_nav_prop} {{ get; set; }}")

        if add_validation_annotations:
            if is_required and not is_pk and not has_default:
                class_code.append('        [Required(ErrorMessage = "Required")]')
            if cs_type == "string" and char_max_len and char_max_len > 0:
                class_code.append(f'        [StringLength({char_max_len}, ErrorMessage = "Max {char_max_len} characters")]')
            if "email" in col_name.lower():
                class_code.append('        [EmailAddress(ErrorMessage = "Invalid email address")]')

        # Property line
        prop_line = f"        public {cs_type}{nullable_marker} {col_name} {{ get; set; }}"
        if not is_nullable_type:
            if cs_type == "string":
                prop_line += " = string.Empty;"
            elif cs_type == "DateTime":
                prop_line += " = DateTime.MinValue;"
            elif cs_type == "decimal":
                prop_line += " = 0m;"
            elif cs_type == "int":
                prop_line += " = 0;"
            elif cs_type == "long":
                prop_line += " = 0L;"
            elif cs_type == "byte":
                prop_line += " = 0;"
            elif cs_type == "Guid":
                prop_line += " = Guid.Empty;"
        class_code.append(prop_line)
        class_code.append("")

    class_code.append("        // Navigation properties")
    class_code.extend(append_class_code)
    class_code.append("    }")
    class_code.append("}")

    # Write file
    out_path = os.path.join(output_dir, f"{class_name}.cs")
    with open(out_path, "w") as f:
        f.write("\n".join(class_code))

cur.close()
conn.close()

